### PR TITLE
[do not merge] Test master build

### PR DESCRIPTION
**Pull request by michielbdejong**

### CODE REVIEW

**Comment by michielbdejong** [comment]
This shows that the tests are failing in master; it's a problem with the constructor of BigNumber. Not sure why it was passing in the past, must be something to do with versions that run on circleci.

**Comment by michielbdejong** [comment]
@KattMingMing any idea how we can fix this?

**Comment by KattMingMing** [comment]
@michielbdejong - Take a look at https://github.com/interledgerjs/ilp-packet/pull/16

**Comment by michielbdejong** [comment]
ha, awesome, thanks!

**Pull request closed without merging**
